// 14 TA HUDUDIY BOSHQARMA BO'YICHA TO'LIQ MATRITSA VA KO'RSATKICHLAR
window.regionsReportData = [
  { id: 'samarqand', name: 'Samarqand viloyati', total: 38, hmmqo: 25, ichki: 13, hmmqo_prok: 2, hmmqo_iib: 1, hmmqo_dxx: 1, hmmqo_other: 0, ichki_prok: 2, ichki_iib: 1, ichki_dxx: 1, ichki_other: 0, hmmqo_crim: 1, hmmqo_adm: 0, hmmqo_83: 0, hmmqo_84: 0, hmmqo_rej: 0, hmmqo_proc: 2, hmmqo_fire: 3, hmmqo_disc: 8, ichki_crim: 1, ichki_adm: 0, ichki_83: 0, ichki_84: 0, ichki_rej: 0, ichki_proc: 1, ichki_fire: 3, ichki_disc: 7, convictedCount: 3, opsCount: 2, riskCount: 4, firedCount: 3, invCount: 38, conflictCount: 4, businessCount: 2, conflictDone: 3, conflictProcess: 1, conflictUndone: 0, riskA: 2, riskB: 1, riskD: 1, agentlik: {done: 8, review: 1, overdue: 0}, palata: {done: 6, review: 0, overdue: 1} },
  { id: 'toshkent_vil', name: 'Toshkent viloyati', total: 32, hmmqo: 20, ichki: 12, hmmqo_prok: 1, hmmqo_iib: 0, hmmqo_dxx: 0, hmmqo_other: 1, ichki_prok: 1, ichki_iib: 1, ichki_dxx: 0, ichki_other: 0, hmmqo_crim: 0, hmmqo_adm: 0, hmmqo_83: 0, hmmqo_84: 0, hmmqo_rej: 0, hmmqo_proc: 1, hmmqo_fire: 2, hmmqo_disc: 7, ichki_crim: 1, ichki_adm: 0, ichki_83: 0, ichki_84: 0, ichki_rej: 0, ichki_proc: 1, ichki_fire: 2, ichki_disc: 6, convictedCount: 4, opsCount: 2, riskCount: 5, firedCount: 2, invCount: 32, conflictCount: 3, businessCount: 1, conflictDone: 2, conflictProcess: 1, conflictUndone: 0, riskA: 2, riskB: 2, riskD: 1, agentlik: {done: 5, review: 1, overdue: 2}, palata: {done: 4, review: 0, overdue: 2} },
  { id: 'andijon', name: 'Andijon viloyati', total: 13, hmmqo: 6, ichki: 7, hmmqo_prok: 3, hmmqo_iib: 3, hmmqo_dxx: 0, hmmqo_other: 0, ichki_prok: 1, ichki_iib: 0, ichki_dxx: 0, ichki_other: 0, hmmqo_crim: 0, hmmqo_adm: 0, hmmqo_83: 0, hmmqo_84: 0, hmmqo_rej: 0, hmmqo_proc: 6, hmmqo_fire: 2, hmmqo_disc: 2, ichki_crim: 0, ichki_adm: 0, ichki_83: 0, ichki_84: 0, ichki_rej: 0, ichki_proc: 4, ichki_fire: 4, ichki_disc: 2, convictedCount: 2, opsCount: 1, riskCount: 3, firedCount: 4, invCount: 13, conflictCount: 3, businessCount: 2, conflictDone: 2, conflictProcess: 1, conflictUndone: 0, riskA: 1, riskB: 1, riskD: 1, agentlik: {done: 7, review: 1, overdue: 0}, palata: {done: 5, review: 1, overdue: 2} },
  { id: 'buxoro', name: 'Buxoro viloyati', total: 16, hmmqo: 3, ichki: 13, hmmqo_prok: 0, hmmqo_iib: 0, hmmqo_dxx: 0, hmmqo_other: 0, ichki_prok: 0, ichki_iib: 0, ichki_dxx: 0, ichki_other: 0, hmmqo_crim: 0, hmmqo_adm: 0, hmmqo_83: 0, hmmqo_84: 0, hmmqo_rej: 0, hmmqo_proc: 0, hmmqo_fire: 0, hmmqo_disc: 0, ichki_crim: 2, ichki_adm: 1, ichki_83: 0, ichki_84: 0, ichki_rej: 0, ichki_proc: 0, ichki_fire: 4, ichki_disc: 3, convictedCount: 1, opsCount: 1, riskCount: 3, firedCount: 2, invCount: 16, conflictCount: 2, businessCount: 1, conflictDone: 1, conflictProcess: 1, conflictUndone: 0, riskA: 1, riskB: 1, riskD: 1, agentlik: {done: 4, review: 0, overdue: 2}, palata: {done: 2, review: 1, overdue: 2} },
  { id: 'xorazm', name: 'Xorazm viloyati', total: 17, hmmqo: 10, ichki: 7, hmmqo_prok: 0, hmmqo_iib: 0, hmmqo_dxx: 0, hmmqo_other: 0, ichki_prok: 0, ichki_iib: 0, ichki_dxx: 0, ichki_other: 0, hmmqo_crim: 0, hmmqo_adm: 0, hmmqo_83: 0, hmmqo_84: 0, hmmqo_rej: 0, hmmqo_proc: 0, hmmqo_fire: 0, hmmqo_disc: 3, ichki_crim: 0, ichki_adm: 0, ichki_83: 0, ichki_84: 0, ichki_rej: 0, ichki_proc: 0, ichki_fire: 1, ichki_disc: 2, convictedCount: 2, opsCount: 1, riskCount: 6, firedCount: 3, invCount: 17, conflictCount: 3, businessCount: 2, conflictDone: 2, conflictProcess: 1, conflictUndone: 0, riskA: 2, riskB: 2, riskD: 2, agentlik: {done: 1, review: 0, overdue: 3}, palata: {done: 1, review: 0, overdue: 3} },
  { id: 'toshkent_sh', name: 'Toshkent shahri', total: 32, hmmqo: 21, ichki: 11, hmmqo_prok: 1, hmmqo_iib: 0, hmmqo_dxx: 0, hmmqo_other: 0, ichki_prok: 0, ichki_iib: 0, ichki_dxx: 0, ichki_other: 0, hmmqo_crim: 0, hmmqo_adm: 0, hmmqo_83: 0, hmmqo_84: 0, hmmqo_rej: 0, hmmqo_proc: 0, hmmqo_fire: 0, hmmqo_disc: 3, ichki_crim: 0, ichki_adm: 0, ichki_83: 0, ichki_84: 0, ichki_rej: 0, ichki_proc: 0, ichki_fire: 1, ichki_disc: 3, convictedCount: 2, opsCount: 2, riskCount: 4, firedCount: 2, invCount: 32, conflictCount: 3, businessCount: 1, conflictDone: 2, conflictProcess: 1, conflictUndone: 0, riskA: 2, riskB: 1, riskD: 1, agentlik: {done: 9, review: 0, overdue: 1}, palata: {done: 8, review: 1, overdue: 0} },
  { id: 'namangan', name: 'Namangan viloyati', total: 24, hmmqo: 15, ichki: 9, hmmqo_prok: 1, hmmqo_iib: 1, hmmqo_dxx: 0, hmmqo_other: 1, ichki_prok: 1, ichki_iib: 0, ichki_dxx: 0, ichki_other: 0, hmmqo_crim: 0, hmmqo_adm: 0, hmmqo_83: 0, hmmqo_84: 0, hmmqo_rej: 0, hmmqo_proc: 2, hmmqo_fire: 1, hmmqo_disc: 6, ichki_crim: 1, ichki_adm: 0, ichki_83: 0, ichki_84: 0, ichki_rej: 0, ichki_proc: 1, ichki_fire: 2, ichki_disc: 5, convictedCount: 1, opsCount: 1, riskCount: 3, firedCount: 2, invCount: 24, conflictCount: 2, businessCount: 1, conflictDone: 1, conflictProcess: 1, conflictUndone: 0, riskA: 1, riskB: 1, riskD: 1, agentlik: {done: 7, review: 0, overdue: 1}, palata: {done: 6, review: 1, overdue: 1} },
  { id: 'fargona', name: 'Farg\'ona viloyati', total: 29, hmmqo: 19, ichki: 10, hmmqo_prok: 1, hmmqo_iib: 1, hmmqo_dxx: 0, hmmqo_other: 0, ichki_prok: 1, ichki_iib: 0, ichki_dxx: 0, ichki_other: 1, hmmqo_crim: 0, hmmqo_adm: 0, hmmqo_83: 0, hmmqo_84: 0, hmmqo_rej: 0, hmmqo_proc: 1, hmmqo_fire: 1, hmmqo_disc: 6, ichki_crim: 1, ichki_adm: 0, ichki_83: 0, ichki_84: 0, ichki_rej: 0, ichki_proc: 0, ichki_fire: 2, ichki_disc: 5, convictedCount: 1, opsCount: 1, riskCount: 4, firedCount: 2, invCount: 29, conflictCount: 2, businessCount: 1, conflictDone: 2, conflictProcess: 0, conflictUndone: 0, riskA: 2, riskB: 1, riskD: 1, agentlik: {done: 6, review: 1, overdue: 1}, palata: {done: 5, review: 0, overdue: 2} },
  { id: 'qashqadaryo', name: 'Qashqadaryo viloyati', total: 28, hmmqo: 18, ichki: 10, hmmqo_prok: 2, hmmqo_iib: 1, hmmqo_dxx: 0, hmmqo_other: 1, ichki_prok: 2, ichki_iib: 1, ichki_dxx: 0, ichki_other: 0, hmmqo_crim: 1, hmmqo_adm: 0, hmmqo_83: 0, hmmqo_84: 0, hmmqo_rej: 0, hmmqo_proc: 3, hmmqo_fire: 2, hmmqo_disc: 5, ichki_crim: 1, ichki_adm: 0, ichki_83: 0, ichki_84: 0, ichki_rej: 0, ichki_proc: 2, ichki_fire: 3, ichki_disc: 4, convictedCount: 1, opsCount: 1, riskCount: 4, firedCount: 2, invCount: 28, conflictCount: 2, businessCount: 1, conflictDone: 1, conflictProcess: 1, conflictUndone: 0, riskA: 2, riskB: 1, riskD: 1, agentlik: {done: 4, review: 1, overdue: 2}, palata: {done: 3, review: 1, overdue: 2} },
  { id: 'surxondaryo', name: 'Surxondaryo viloyati', total: 22, hmmqo: 14, ichki: 8, hmmqo_prok: 1, hmmqo_iib: 1, hmmqo_dxx: 0, hmmqo_other: 0, ichki_prok: 0, ichki_iib: 0, ichki_dxx: 0, ichki_other: 0, hmmqo_crim: 0, hmmqo_adm: 0, hmmqo_83: 0, hmmqo_84: 0, hmmqo_rej: 0, hmmqo_proc: 1, hmmqo_fire: 1, hmmqo_disc: 5, ichki_crim: 0, ichki_adm: 0, ichki_83: 0, ichki_84: 0, ichki_rej: 0, ichki_proc: 1, ichki_fire: 1, ichki_disc: 4, convictedCount: 1, opsCount: 1, riskCount: 3, firedCount: 1, invCount: 22, conflictCount: 2, businessCount: 1, conflictDone: 1, conflictProcess: 1, conflictUndone: 0, riskA: 1, riskB: 1, riskD: 1, agentlik: {done: 5, review: 0, overdue: 2}, palata: {done: 4, review: 1, overdue: 2} },
  { id: 'jizzax', name: 'Jizzax viloyati', total: 36, hmmqo: 21, ichki: 15, hmmqo_prok: 1, hmmqo_iib: 1, hmmqo_dxx: 0, hmmqo_other: 0, ichki_prok: 0, ichki_iib: 0, ichki_dxx: 0, ichki_other: 0, hmmqo_crim: 0, hmmqo_adm: 0, hmmqo_83: 0, hmmqo_84: 0, hmmqo_rej: 0, hmmqo_proc: 0, hmmqo_fire: 0, hmmqo_disc: 2, ichki_crim: 0, ichki_adm: 0, ichki_83: 0, ichki_84: 0, ichki_rej: 0, ichki_proc: 0, ichki_fire: 0, ichki_disc: 8, convictedCount: 0, opsCount: 0, riskCount: 3, firedCount: 1, invCount: 36, conflictCount: 1, businessCount: 0, conflictDone: 1, conflictProcess: 0, conflictUndone: 0, riskA: 1, riskB: 1, riskD: 1, agentlik: {done: 3, review: 1, overdue: 2}, palata: {done: 2, review: 0, overdue: 3} },
  { id: 'sirdaryo', name: 'Sirdaryo viloyati', total: 15, hmmqo: 10, ichki: 5, hmmqo_prok: 0, hmmqo_iib: 0, hmmqo_dxx: 0, hmmqo_other: 1, ichki_prok: 0, ichki_iib: 0, ichki_dxx: 0, ichki_other: 1, hmmqo_crim: 0, hmmqo_adm: 0, hmmqo_83: 0, hmmqo_84: 0, hmmqo_rej: 0, hmmqo_proc: 1, hmmqo_fire: 1, hmmqo_disc: 3, ichki_crim: 0, ichki_adm: 0, ichki_83: 0, ichki_84: 0, ichki_rej: 0, ichki_proc: 1, ichki_fire: 1, ichki_disc: 3, convictedCount: 0, opsCount: 0, riskCount: 2, firedCount: 1, invCount: 15, conflictCount: 1, businessCount: 1, conflictDone: 1, conflictProcess: 0, conflictUndone: 0, riskA: 1, riskB: 1, riskD: 0, agentlik: {done: 3, review: 0, overdue: 2}, palata: {done: 3, review: 1, overdue: 2} },
  { id: 'navoiy', name: 'Navoiy viloyati', total: 18, hmmqo: 11, ichki: 7, hmmqo_prok: 1, hmmqo_iib: 0, hmmqo_dxx: 1, hmmqo_other: 0, ichki_prok: 0, ichki_iib: 0, ichki_dxx: 0, ichki_other: 0, hmmqo_crim: 0, hmmqo_adm: 0, hmmqo_83: 0, hmmqo_84: 0, hmmqo_rej: 0, hmmqo_proc: 1, hmmqo_fire: 1, hmmqo_disc: 4, ichki_crim: 0, ichki_adm: 0, ichki_83: 0, ichki_84: 0, ichki_rej: 0, ichki_proc: 1, ichki_fire: 2, ichki_disc: 3, convictedCount: 0, opsCount: 1, riskCount: 2, firedCount: 1, invCount: 18, conflictCount: 1, businessCount: 1, conflictDone: 1, conflictProcess: 0, conflictUndone: 0, riskA: 1, riskB: 0, riskD: 1, agentlik: {done: 6, review: 1, overdue: 1}, palata: {done: 5, review: 0, overdue: 1} },
  { id: 'qr', name: 'Qoraqalpog\'iston Resp.', total: 12, hmmqo: 7, ichki: 5, hmmqo_prok: 0, hmmqo_iib: 0, hmmqo_dxx: 0, hmmqo_other: 0, ichki_prok: 0, ichki_iib: 0, ichki_dxx: 0, ichki_other: 0, hmmqo_crim: 0, hmmqo_adm: 0, hmmqo_83: 0, hmmqo_84: 0, hmmqo_rej: 0, hmmqo_proc: 0, hmmqo_fire: 0, hmmqo_disc: 1, ichki_crim: 0, ichki_adm: 0, ichki_83: 0, ichki_84: 0, ichki_rej: 0, ichki_proc: 0, ichki_fire: 3, ichki_disc: 0, convictedCount: 0, opsCount: 0, riskCount: 2, firedCount: 0, invCount: 12, conflictCount: 1, businessCount: 0, conflictDone: 1, conflictProcess: 0, conflictUndone: 0, riskA: 0, riskB: 1, riskD: 1, agentlik: {done: 4, review: 1, overdue: 2}, palata: {done: 4, review: 0, overdue: 2} }
];

// ANIQ HUDUDIY VA GEOGRAFIK TO'G'RI BO'LGAN TUMANLAR VA XODIMLAR BAZASI
window.deepDrillDatabase = {
  'investigations': [
    { region: 'Samarqand viloyati', wing: 'agentlik', district: 'Pastdarg\'om tuman filiali', officer: 'Aliyev Mansur G\'aniyevich', pinfl: '31804901230011', role: 'Bo\'lim boshlig\'i', reason: '1.5 gektar ekin yerini noturar joy toifasiga o\'tkazish', code: 'XT-SAM-081', date: '21.09.2026', docType: 'investigation' },
    { region: 'Samarqand viloyati', wing: 'palata', district: 'Urgut tuman filiali', officer: 'Rustamov Bobur Shokirovich', pinfl: '32001881230022', role: 'Yetakchi muhandis', reason: 'Yer chegaralarini asossiz o\'zgartirib dalolatnoma tuzish', code: 'XT-SAM-094', date: '15.09.2026', docType: 'investigation' },
    { region: 'Toshkent viloyati', wing: 'agentlik', district: 'Qibray tumani filiali', officer: 'Ergashev Tohir Mansurovich', pinfl: '31904881120021', role: 'Bosh muhandis', reason: 'Auksionsiz berilgan bino-inshootga sun\'iy kadastr ochish', code: 'XT-TOS-033', date: '08.08.2026', docType: 'investigation' },
    { region: 'Toshkent viloyati', wing: 'palata', district: 'Zangiota tuman filiali', officer: 'Karimov Jasur Shukurovich', pinfl: '32401912230011', role: 'Davlat ro\'yxatidan o\'tkazuvchi', reason: 'Ko\'chmas mulk bazasiga ruxsatsiz o\'zgartirish kiritish', code: 'XT-TOS-051', date: '19.09.2026', docType: 'investigation' },
    { region: 'Andijon viloyati', wing: 'palata', district: 'Asaka tuman filiali', officer: 'Qodirov Farrux Rustamovich', pinfl: '32501913340078', role: 'Arxiv mudiri', reason: 'Yer kadastri arxiv hujjatlarini soxtalashtirish', code: 'XT-AND-012', date: '11.07.2026', docType: 'investigation' },
    { region: 'Buxoro viloyati', wing: 'agentlik', district: 'G\'ijduvon tuman filiali', officer: 'Nazarov Ilhom Bobirovich', pinfl: '31802956730055', role: 'Katta inspektor', reason: 'Tadbirkordan hujjat tasdiqlash uchun mablag\' talab qilish', code: 'XT-BUX-044', date: '28.08.2026', docType: 'investigation' },
    { region: 'Farg\'ona viloyati', wing: 'palata', district: 'Quva tuman filiali', officer: 'Mamatov Doniyor Zokirovich', pinfl: '32109881120099', role: 'Yer tuzuvchi', reason: 'Mulk chegarasini qo\'shni uchastka hisobiga noqonuniy kengaytirish', code: 'XT-FAR-019', date: '04.09.2026', docType: 'investigation' },
    { region: 'Qashqadaryo viloyati', wing: 'agentlik', district: 'Koson tuman filiali', officer: 'Oripov Bobur Karimovich', pinfl: '31901874430066', role: 'Filial boshlig\'i', reason: 'Zaxira yer maydonini komissiya xulosasisiz ro\'yxatdan o\'tkazish', code: 'XT-QASH-008', date: '18.08.2026', docType: 'investigation' }
  ],
  'convicted': [
    { region: 'Toshkent viloyati', wing: 'agentlik', district: 'Qibray tumani filiali', officer: 'Ergashev Tohir Mansurovich', pinfl: '31904881120021', role: 'Yetakchi muhandis', reason: '168-m 3-qism, 205-m (Firibgarlik va mansab suiiste\'moli)', code: 'SUD-TOS-019', date: '18.04.2025', court: 'Qibray tuman sudi', status: 'chetlatilgan', docType: 'court' },
    { region: 'Samarqand viloyati', wing: 'palata', district: 'Samarqand shahar filiali', officer: 'Aliyev Vali G\'aniyevich', pinfl: '32004881120034', role: 'Davlat ro\'yxatidan o\'tkazuvchi', reason: '167-m, 210-m (Pora olish)', code: 'SUD-SAM-007', date: '12.03.2024', court: 'Samarqand shahar JIB sudi', status: 'chetlatilgan', docType: 'court' },
    { region: 'Andijon viloyati', wing: 'palata', district: 'Asaka tuman filiali', officer: 'Qodirov Farrux Rustamovich', pinfl: '32501913340078', role: 'Arxiv mudiri', reason: '209-modda (Xizmat soxtakorligi)', code: 'SUD-AND-031', date: '15.02.2026', court: 'Andijon shahar sudi', status: 'chetlatilgan', docType: 'court' },
    { region: 'Buxoro viloyati', wing: 'agentlik', district: 'Buxoro shahar filiali', officer: 'Sobirov Odil Mirzoyevich', pinfl: '31705891120088', role: 'Inspektor', reason: '210-modda (Katta miqdorda pora olish)', code: 'SUD-BUX-014', date: '20.06.2025', court: 'Buxoro viloyat sudi', status: 'chetlatilgan', docType: 'court' }
  ],
  'operations': [
    { region: 'Samarqand viloyati', wing: 'agentlik', district: 'Pastdarg\'om tuman filiali', officer: 'Filial boshlig\'i o\'rinbosari', pinfl: '32104921230055', role: 'Muhandis', partner: 'Davlat Xavfsizlik Xizmati (DXX)', isCollab: true, proof: '3,000 AQSH dollari', reason: 'Ekin yerini noturar joy toifasiga o\'tkazish evaziga pora', code: 'TT-SAM-08', date: '18.09.2026', docType: 'operation' },
    { region: 'Toshkent viloyati', wing: 'palata', district: 'Zangiota tuman filiali', officer: 'Ro\'yxatga oluvchi mutaxassis', pinfl: '31908851440019', role: 'Yetakchi mutaxassis', partner: 'Bosh prokuratura huzuridagi Departament', isCollab: true, proof: '2,500 AQSH dollari', reason: 'Uy-joy chegaralarini noqonuniy kengaytirib rasmiylashtirish', code: 'TT-TOS-09', date: '12.09.2026', docType: 'operation' },
    { region: 'Andijon viloyati', wing: 'agentlik', district: 'Asaka tuman filiali', officer: 'Bosh mutaxassis', pinfl: '32501913340078', role: 'Yetakchi muhandis', partner: 'Ichki Ishlar Vazirligi (IIB)', isCollab: true, proof: '1,200 AQSH dollari', reason: 'Yakka tartibda qurilgan uyga o\'zboshimchalik bilan kadastr berish', code: 'TT-AND-02', date: '14.07.2026', docType: 'operation' }
  ],
  'risk': [
    { region: 'Samarqand viloyati', wing: 'palata', district: 'Samarqand shahar filiali', officer: 'Rahmonov Dilshod Anvarovich', pinfl: '32104921230055', role: 'Mulkni ro\'yxatga olish bo\'lim boshlig\'i', type: 'A', reason: 'Yer maydonlarini auksionsiz o\'tkazish va noqonuniy xususiylashtirish xavfi yuqori', action: 'Video/audio nazorat ostida, imzo huquqi cheklandi', code: 'XAVF-SAM-01', date: '12.09.2026', docType: 'risk' },
    { region: 'Samarqand viloyati', wing: 'agentlik', district: 'Toyloq tuman filiali', officer: 'Valiyev Sardor Olimovich', pinfl: '31804901230077', role: 'Katta muhandis', type: 'B', reason: 'Qarindoshlik va tijorat subyektlari bilan bevosita manfaatdorlik aloqasi', action: 'Boshqa tuman filialiga rotatsiya qilish tavsiya etildi', code: 'XAVF-SAM-04', date: '19.08.2026', docType: 'risk' },
    { region: 'Toshkent viloyati', wing: 'agentlik', district: 'Qibray tumani filiali', officer: 'Ergashev Bobur Tohirovich', pinfl: '31908851440019', role: 'Bosh muhandis', type: 'A', reason: 'Qurilish korxonalari bilan doimiy shubhali yashirin aloqalar', action: 'Imzo vakolati to\'xtatilgan, xizmat tekshiruvi tayinlangan', code: 'XAVF-TOS-04', date: '18.09.2026', docType: 'risk' },
    { region: 'Toshkent viloyati', wing: 'palata', district: 'Toshkent tumani filiali', officer: 'Nizomov Akmal Botirovich', pinfl: '32305912230044', role: 'Ro\'yxatdan o\'tkazuvchi', type: 'D', reason: 'Hujjatlarni o\'z vaqtida ro\'yxatga olmaslik va ijro intizomi sustligi', action: 'Profilaktik ogohlantirish berildi', code: 'XAVF-TOS-09', date: '02.09.2026', docType: 'risk' },
    { region: 'Andijon viloyati', wing: 'agentlik', district: 'Asaka tuman filiali', officer: 'Karimov Jasur Shukurovich', pinfl: '32401912230011', role: 'Yetakchi mutaxassis', type: 'B', reason: 'Yaqin qarindoshi xususiy kadastr loyihalash tashkilotida ta\'sischi', action: 'Tasdiqlash komissiyasi a\'zoligidan chiqarilgan', code: 'XAVF-AND-02', date: '05.08.2026', docType: 'risk' }
  ],
  'fired': [
    { region: 'Samarqand viloyati', wing: 'agentlik', district: 'Urgut tuman filiali', officer: 'Sultonov Murod G\'aniyevich', pinfl: '31804901230077', role: 'Yetakchi inspektor', reason: 'Egallangan yerga asossiz ravishda soxta kadastr pasporti shakllantirgan', orderNum: '№144-K', date: '14.08.2026', docType: 'fired' },
    { region: 'Toshkent viloyati', wing: 'palata', district: 'Zangiota tuman filiali', officer: 'Bekmurodov Sanjar Alisherovich', pinfl: '31405901230018', role: 'Davlat ro\'yxatidan o\'tkazuvchi', reason: 'Tadbirkordan hujjatlarni o\'tkazish evaziga noqonuniy haq talab qilganligi isbotlangan', orderNum: '№98-K', date: '28.07.2026', docType: 'fired' },
    { region: 'Andijon viloyati', wing: 'palata', district: 'Asaka tuman filiali', officer: 'Yusupov Jamshid Tohirovich', pinfl: '32109881120055', role: 'Bo\'lim mudiri', reason: 'Tadbirkorlik (MCHJ) ta\'sischisi ekanligi fosh bo\'lib, tugatishdan bosh tortgan', orderNum: '№112-K', date: '02.09.2026', docType: 'fired' }
  ]
};

// TOPSHIRIQLAR REYESTRI
window.tasksData = [
  { id: 'T-SAM-01', region: 'Samarqand viloyati', target: 'Kadastr Agentligi viloyat boshqarmasi', title: 'Pastdarg\'om tumanidagi ekin yerlarini to\'liq xatlovdan o\'tkazish', date: '10.09.2026', deadline: '25.09.2026', status: 'Bajarildi' },
  { id: 'T-SAM-02', region: 'Samarqand viloyati', target: 'Kadastrlar Palatasi viloyat boshqarmasi', title: 'Urgut filiali arxiv hujjatlarini raqamlashtirish intizomi', date: '15.09.2026', deadline: '05.10.2026', status: 'Jarayonda' },
  { id: 'T-TOS-01', region: 'Toshkent viloyati', target: 'Kadastr Agentligi viloyat boshqarmasi', title: 'Qibray tumani bino pasportlari haqqoniyligi auditi', date: '12.09.2026', deadline: '28.09.2026', status: 'Bajarildi' },
  { id: 'T-TOS-02', region: 'Toshkent viloyati', target: 'Kadastrlar Palatasi viloyat boshqarmasi', title: 'Zangiota tumanida auksionsiz berilgan yerlar tekshiruvi', date: '05.09.2026', deadline: '22.09.2026', status: 'Kechikkan' },
  { id: 'T-AND-01', region: 'Andijon viloyati', target: 'Kadastr Agentligi viloyat boshqarmasi', title: 'Asaka tuman filiali yer ajratish monitoringi', date: '14.09.2026', deadline: '30.09.2026', status: 'Bajarildi' }
];

// SUDLANGANLAR RO'YXATI
window.convictedData = [
  { pinfl: '31904881120021', name: 'Ergashev Tohir Mansurovich', region: 'Toshkent viloyati', role: 'Yetakchi muhandis', court: 'Qibray tuman sudi', date: '18.04.2025', articles: '168-m, 205-m', punishment: 'Ozodlikni cheklash, mansab taqiqi', status: 'chetlatilgan' },
  { pinfl: '32004881120034', name: 'Aliyev Vali G\'aniyevich', region: 'Samarqand viloyati', role: 'Davlat ro\'yxatidan o\'tkazuvchi', court: 'Samarqand shahar sudi', date: '12.03.2024', articles: '167-m, 210-m', punishment: 'Jarima va moddiy zarar', status: 'chetlatilgan' },
  { pinfl: '32501913340078', name: 'Qodirov Farrux Rustamovich', region: 'Andijon viloyati', role: 'Arxiv mudiri', court: 'Andijon shahar sudi', date: '15.02.2026', articles: '209-modda', punishment: 'Ozodlikni cheklash', status: 'chetlatilgan' }
];

// MANFAATLAR TO'QNASHUVI VA TADBIRKORLIK (STIR) RO'YXATI
window.combinedConflictBusinessData = [
  { name: 'Sobirov Mirkomil Rustamovich', pinfl: '31506891230041', region: 'Andijon viloyati', role: '1-toifali mutaxassis', type: 'Tadbirkorlik (STIR)', detail: '"VODIY GEO LOYIHA" MCHJ (STIR: 308291442) 50% ta\'sischisi', action: 'Ulushdan chiqish talabnomasi berilgan' },
  { name: 'Rahmonov Dilshod Anvarovich', pinfl: '32104921230055', region: 'Samarqand viloyati', role: 'Bo\'lim boshlig\'i', type: 'Manfaatlar to\'qnashuvi', detail: 'Ukasi Rahmonov Sanjar — xususiy kadastr muhandisi', action: 'Boshqa tuman filialiga rotatsiya qilingan' },
  { name: 'Ergashev Bobur Tohirovich', pinfl: '31908851440019', region: 'Toshkent viloyati', role: 'Bosh mutaxassis', type: 'Manfaatlar to\'qnashuvi', detail: 'Ayoli Tohirova Madina — rieltorlik agentligi rahbari', action: 'Tasdiqlash komissiyasidan chetlatilgan' },
  { name: 'Valiyev Sardor Olimovich', pinfl: '31804901230077', region: 'Samarqand viloyati', role: 'Arxiv mudiri', type: 'Tadbirkorlik (STIR)', detail: '"SAMARQAND AGRO" MCHJ (STIR: 305119842) 25% ulush', action: 'Tadbirkorlikni to\'xtatish to\'g'risida ogohlantirilgan' }
];
