// 14 TA HUDUDIY BOSHQARMA BO'YICHA TO'LIQ STATISTIKA VA MATRITSA MA'LUMOTLARI
window.regionsReportData = [
  { id: 'samarqand', name: 'Samarqand viloyati', total: 38, hmmqo: 25, ichki: 13, hmmqo_prok: 2, hmmqo_iib: 1, hmmqo_dxx: 1, hmmqo_other: 0, ichki_prok: 2, ichki_iib: 1, ichki_dxx: 1, ichki_other: 0, hmmqo_crim: 1, hmmqo_adm: 0, hmmqo_83: 0, hmmqo_84: 0, hmmqo_rej: 0, hmmqo_proc: 2, hmmqo_fire: 3, hmmqo_disc: 8, ichki_crim: 1, ichki_adm: 0, ichki_83: 0, ichki_84: 0, ichki_rej: 0, ichki_proc: 1, ichki_fire: 3, ichki_disc: 7, convictedCount: 3, opsCount: 2, riskCount: 4, firedCount: 3, invCount: 38, conflictCount: 2, businessCount: 2, agentlik: {done: 8, review: 1, overdue: 0}, palata: {done: 6, review: 0, overdue: 1} },
  { id: 'toshkent_vil', name: 'Toshkent viloyati', total: 32, hmmqo: 20, ichki: 12, hmmqo_prok: 1, hmmqo_iib: 0, hmmqo_dxx: 0, hmmqo_other: 1, ichki_prok: 1, ichki_iib: 1, ichki_dxx: 0, ichki_other: 0, hmmqo_crim: 0, hmmqo_adm: 0, hmmqo_83: 0, hmmqo_84: 0, hmmqo_rej: 0, hmmqo_proc: 1, hmmqo_fire: 2, hmmqo_disc: 7, ichki_crim: 1, ichki_adm: 0, ichki_83: 0, ichki_84: 0, ichki_rej: 0, ichki_proc: 1, ichki_fire: 2, ichki_disc: 6, convictedCount: 4, opsCount: 2, riskCount: 5, firedCount: 2, invCount: 32, conflictCount: 2, businessCount: 1, agentlik: {done: 5, review: 1, overdue: 2}, palata: {done: 4, review: 0, overdue: 2} },
  { id: 'andijon', name: 'Andijon viloyati', total: 13, hmmqo: 6, ichki: 7, hmmqo_prok: 3, hmmqo_iib: 3, hmmqo_dxx: 0, hmmqo_other: 0, ichki_prok: 1, ichki_iib: 0, ichki_dxx: 0, ichki_other: 0, hmmqo_crim: 0, hmmqo_adm: 0, hmmqo_83: 0, hmmqo_84: 0, hmmqo_rej: 0, hmmqo_proc: 6, hmmqo_fire: 2, hmmqo_disc: 2, ichki_crim: 0, ichki_adm: 0, ichki_83: 0, ichki_84: 0, ichki_rej: 0, ichki_proc: 4, ichki_fire: 4, ichki_disc: 2, convictedCount: 2, opsCount: 1, riskCount: 3, firedCount: 4, invCount: 13, conflictCount: 1, businessCount: 2, agentlik: {done: 7, review: 1, overdue: 0}, palata: {done: 5, review: 1, overdue: 2} },
  { id: 'buxoro', name: 'Buxoro viloyati', total: 16, hmmqo: 3, ichki: 13, hmmqo_prok: 0, hmmqo_iib: 0, hmmqo_dxx: 0, hmmqo_other: 0, ichki_prok: 0, ichki_iib: 0, ichki_dxx: 0, ichki_other: 0, hmmqo_crim: 0, hmmqo_adm: 0, hmmqo_83: 0, hmmqo_84: 0, hmmqo_rej: 0, hmmqo_proc: 0, hmmqo_fire: 0, hmmqo_disc: 0, ichki_crim: 2, ichki_adm: 1, ichki_83: 0, ichki_84: 0, ichki_rej: 0, ichki_proc: 0, ichki_fire: 4, ichki_disc: 3, convictedCount: 1, opsCount: 1, riskCount: 3, firedCount: 2, invCount: 16, conflictCount: 1, businessCount: 1, agentlik: {done: 4, review: 0, overdue: 2}, palata: {done: 2, review: 1, overdue: 2} },
  { id: 'xorazm', name: 'Xorazm viloyati', total: 17, hmmqo: 10, ichki: 7, hmmqo_prok: 0, hmmqo_iib: 0, hmmqo_dxx: 0, hmmqo_other: 0, ichki_prok: 0, ichki_iib: 0, ichki_dxx: 0, ichki_other: 0, hmmqo_crim: 0, hmmqo_adm: 0, hmmqo_83: 0, hmmqo_84: 0, hmmqo_rej: 0, hmmqo_proc: 0, hmmqo_fire: 0, hmmqo_disc: 3, ichki_crim: 0, ichki_adm: 0, ichki_83: 0, ichki_84: 0, ichki_rej: 0, ichki_proc: 0, ichki_fire: 1, ichki_disc: 2, convictedCount: 2, opsCount: 1, riskCount: 6, firedCount: 3, invCount: 17, conflictCount: 1, businessCount: 2, agentlik: {done: 1, review: 0, overdue: 3}, palata: {done: 1, review: 0, overdue: 3} },
  { id: 'toshkent_sh', name: 'Toshkent shahri', total: 32, hmmqo: 21, ichki: 11, hmmqo_prok: 1, hmmqo_iib: 0, hmmqo_dxx: 0, hmmqo_other: 0, ichki_prok: 0, ichki_iib: 0, ichki_dxx: 0, ichki_other: 0, hmmqo_crim: 0, hmmqo_adm: 0, hmmqo_83: 0, hmmqo_84: 0, hmmqo_rej: 0, hmmqo_proc: 0, hmmqo_fire: 0, hmmqo_disc: 3, ichki_crim: 0, ichki_adm: 0, ichki_83: 0, ichki_84: 0, ichki_rej: 0, ichki_proc: 0, ichki_fire: 1, ichki_disc: 3, convictedCount: 2, opsCount: 2, riskCount: 4, firedCount: 2, invCount: 32, conflictCount: 2, businessCount: 1, agentlik: {done: 9, review: 0, overdue: 1}, palata: {done: 8, review: 1, overdue: 0} },
  { id: 'namangan', name: 'Namangan viloyati', total: 24, hmmqo: 15, ichki: 9, hmmqo_prok: 1, hmmqo_iib: 1, hmmqo_dxx: 0, hmmqo_other: 1, ichki_prok: 1, ichki_iib: 0, ichki_dxx: 0, ichki_other: 0, hmmqo_crim: 0, hmmqo_adm: 0, hmmqo_83: 0, hmmqo_84: 0, hmmqo_rej: 0, hmmqo_proc: 2, hmmqo_fire: 1, hmmqo_disc: 6, ichki_crim: 1, ichki_adm: 0, ichki_83: 0, ichki_84: 0, ichki_rej: 0, ichki_proc: 1, ichki_fire: 2, ichki_disc: 5, convictedCount: 1, opsCount: 1, riskCount: 3, firedCount: 2, invCount: 24, conflictCount: 1, businessCount: 1, agentlik: {done: 7, review: 0, overdue: 1}, palata: {done: 6, review: 1, overdue: 1} },
  { id: 'fargona', name: 'Farg\'ona viloyati', total: 29, hmmqo: 19, ichki: 10, hmmqo_prok: 1, hmmqo_iib: 1, hmmqo_dxx: 0, hmmqo_other: 0, ichki_prok: 1, ichki_iib: 0, ichki_dxx: 0, ichki_other: 1, hmmqo_crim: 0, hmmqo_adm: 0, hmmqo_83: 0, hmmqo_84: 0, hmmqo_rej: 0, hmmqo_proc: 1, hmmqo_fire: 1, hmmqo_disc: 6, ichki_crim: 1, ichki_adm: 0, ichki_83: 0, ichki_84: 0, ichki_rej: 0, ichki_proc: 0, ichki_fire: 2, ichki_disc: 5, convictedCount: 1, opsCount: 1, riskCount: 4, firedCount: 2, invCount: 29, conflictCount: 1, businessCount: 1, agentlik: {done: 6, review: 1, overdue: 1}, palata: {done: 5, review: 0, overdue: 2} },
  { id: 'qashqadaryo', name: 'Qashqadaryo viloyati', total: 28, hmmqo: 18, ichki: 10, hmmqo_prok: 2, hmmqo_iib: 1, hmmqo_dxx: 0, hmmqo_other: 1, ichki_prok: 2, ichki_iib: 1, ichki_dxx: 0, ichki_other: 0, hmmqo_crim: 1, hmmqo_adm: 0, hmmqo_83: 0, hmmqo_84: 0, hmmqo_rej: 0, hmmqo_proc: 3, hmmqo_fire: 2, hmmqo_disc: 5, ichki_crim: 1, ichki_adm: 0, ichki_83: 0, ichki_84: 0, ichki_rej: 0, ichki_proc: 2, ichki_fire: 3, ichki_disc: 4, convictedCount: 1, opsCount: 1, riskCount: 4, firedCount: 2, invCount: 28, conflictCount: 1, businessCount: 1, agentlik: {done: 4, review: 1, overdue: 2}, palata: {done: 3, review: 1, overdue: 2} },
  { id: 'surxondaryo', name: 'Surxondaryo viloyati', total: 22, hmmqo: 14, ichki: 8, hmmqo_prok: 1, hmmqo_iib: 1, hmmqo_dxx: 0, hmmqo_other: 0, ichki_prok: 0, ichki_iib: 0, ichki_dxx: 0, ichki_other: 0, hmmqo_crim: 0, hmmqo_adm: 0, hmmqo_83: 0, hmmqo_84: 0, hmmqo_rej: 0, hmmqo_proc: 1, hmmqo_fire: 1, hmmqo_disc: 5, ichki_crim: 0, ichki_adm: 0, ichki_83: 0, ichki_84: 0, ichki_rej: 0, ichki_proc: 1, ichki_fire: 1, ichki_disc: 4, convictedCount: 1, opsCount: 1, riskCount: 3, firedCount: 1, invCount: 22, conflictCount: 1, businessCount: 1, agentlik: {done: 5, review: 0, overdue: 2}, palata: {done: 4, review: 1, overdue: 2} },
  { id: 'jizzax', name: 'Jizzax viloyati', total: 36, hmmqo: 21, ichki: 15, hmmqo_prok: 1, hmmqo_iib: 1, hmmqo_dxx: 0, hmmqo_other: 0, ichki_prok: 0, ichki_iib: 0, ichki_dxx: 0, ichki_other: 0, hmmqo_crim: 0, hmmqo_adm: 0, hmmqo_83: 0, hmmqo_84: 0, hmmqo_rej: 0, hmmqo_proc: 0, hmmqo_fire: 0, hmmqo_disc: 2, ichki_crim: 0, ichki_adm: 0, ichki_83: 0, ichki_84: 0, ichki_rej: 0, ichki_proc: 0, ichki_fire: 0, ichki_disc: 8, convictedCount: 0, opsCount: 0, riskCount: 3, firedCount: 1, invCount: 36, conflictCount: 1, businessCount: 0, agentlik: {done: 3, review: 1, overdue: 2}, palata: {done: 2, review: 0, overdue: 3} },
  { id: 'sirdaryo', name: 'Sirdaryo viloyati', total: 15, hmmqo: 10, ichki: 5, hmmqo_prok: 0, hmmqo_iib: 0, hmmqo_dxx: 0, hmmqo_other: 1, ichki_prok: 0, ichki_iib: 0, ichki_dxx: 0, ichki_other: 1, hmmqo_crim: 0, hmmqo_adm: 0, hmmqo_83: 0, hmmqo_84: 0, hmmqo_rej: 0, hmmqo_proc: 1, hmmqo_fire: 1, hmmqo_disc: 3, ichki_crim: 0, ichki_adm: 0, ichki_83: 0, ichki_84: 0, ichki_rej: 0, ichki_proc: 1, ichki_fire: 1, ichki_disc: 3, convictedCount: 0, opsCount: 0, riskCount: 2, firedCount: 1, invCount: 15, conflictCount: 0, businessCount: 1, agentlik: {done: 3, review: 0, overdue: 2}, palata: {done: 3, review: 1, overdue: 2} },
  { id: 'navoiy', name: 'Navoiy viloyati', total: 18, hmmqo: 11, ichki: 7, hmmqo_prok: 1, hmmqo_iib: 0, hmmqo_dxx: 1, hmmqo_other: 0, ichki_prok: 0, ichki_iib: 0, ichki_dxx: 0, ichki_other: 0, hmmqo_crim: 0, hmmqo_adm: 0, hmmqo_83: 0, hmmqo_84: 0, hmmqo_rej: 0, hmmqo_proc: 1, hmmqo_fire: 1, hmmqo_disc: 4, ichki_crim: 0, ichki_adm: 0, ichki_83: 0, ichki_84: 0, ichki_rej: 0, ichki_proc: 1, ichki_fire: 2, ichki_disc: 3, convictedCount: 0, opsCount: 1, riskCount: 2, firedCount: 1, invCount: 18, conflictCount: 0, businessCount: 1, agentlik: {done: 6, review: 1, overdue: 1}, palata: {done: 5, review: 0, overdue: 1} },
  { id: 'qr', name: 'Qoraqalpog\'iston Resp.', total: 12, hmmqo: 7, ichki: 5, hmmqo_prok: 0, hmmqo_iib: 0, hmmqo_dxx: 0, hmmqo_other: 0, ichki_prok: 0, ichki_iib: 0, ichki_dxx: 0, ichki_other: 0, hmmqo_crim: 0, hmmqo_adm: 0, hmmqo_83: 0, hmmqo_84: 0, hmmqo_rej: 0, hmmqo_proc: 0, hmmqo_fire: 0, hmmqo_disc: 1, ichki_crim: 0, ichki_adm: 0, ichki_83: 0, ichki_84: 0, ichki_rej: 0, ichki_proc: 0, ichki_fire: 3, ichki_disc: 0, convictedCount: 0, opsCount: 0, riskCount: 2, firedCount: 0, invCount: 12, conflictCount: 1, businessCount: 0, agentlik: {done: 4, review: 1, overdue: 2}, palata: {done: 4, review: 0, overdue: 2} }
];

// XIZMAT TEKSHIRUVLARI REYESTRI (333 TA ISHDAN NAMUNALAR)
window.investigationsData = [
  { code: '#XT-2026-019', date: '12.08.2026', region: 'Qashqadaryo viloyati', branch: 'Koson filiali', officer: 'Filial boshlig\'i', type: 'Ichki Nazorat', reason: 'Yer maydonini soxta hujjatlar bilan noqonuniy ro\'yxatga olish', result: 'Prokuraturaga yuborilgan (Jinoyat ishi)' },
  { code: '#XT-2026-022', date: '03.09.2026', region: 'Farg\'ona viloyati', branch: 'Quva filiali', officer: 'Muhandis-yer tuzuvchi', type: 'HMMQO Xati (IIB)', reason: 'Yaqin qarindoshiga tegishli MCHJga kadastr pasportini navbatsiz tayyorlash', result: 'Mehnat shartnomasi bekor qilingan' },
  { code: '#XT-2026-031', date: '15.09.2026', region: 'Samarqand viloyati', branch: 'Urgut filiali', officer: 'Yetakchi mutaxassis', type: 'Ichki Nazorat', reason: 'Yer chegaralarini o\'zboshimchalik bilan o\'zgartirib dalolatnoma tuzish', result: 'Intizomiy jazo (Hayfsan)' },
  { code: '#XT-2026-038', date: '21.09.2026', region: 'Samarqand viloyati', branch: 'Pastdarg\'om filiali', officer: 'Bo\'lim boshlig\'i', type: 'HMMQO Xati (DXX)', reason: '1.5 gektar ekin yerini noqonuniy noturar toifaga o\'tkazish', result: 'Lavozimidan ozod etilgan, tergovda' },
  { code: '#XT-2026-042', date: '08.08.2026', region: 'Toshkent viloyati', branch: 'Qibray tumani filiali', officer: 'Bosh muhandis', type: 'HMMQO Xati (Departament)', reason: 'Auksionsiz berilgan bino-inshootga sun\'iy kadastr raqami shakllantirish', result: 'Mehnat shartnomasi bekor qilingan' },
  { code: '#XT-2026-049', date: '19.09.2026', region: 'Toshkent viloyati', branch: 'Zangiota filiali', officer: 'Davlat ro\'yxatidan o\'tkazuvchi', type: 'Ichki Nazorat', reason: 'Ko\'chmas mulk bazasiga asossiz o\'zgartirish kiritish', result: 'Intizomiy jazo (Jarima)' },
  { code: '#XT-2026-055', date: '11.07.2026', region: 'Andijon viloyati', branch: 'Asaka filiali', officer: 'Arxiv mudiri', type: 'HMMQO Xati (IIB)', reason: 'Yer kadastri arxiv hujjatlarini yo\'qotish va soxtalashtirish', result: 'Mehnat shartnomasi bekor qilingan' },
  { code: '#XT-2026-061', date: '28.08.2026', region: 'Buxoro viloyati', branch: 'G\'ijduvon filiali', officer: 'Katta inspektor', type: 'Ichki Nazorat', reason: 'Tadbirkordan hujjat tasdiqlash uchun noqonuniy mablag\' talab qilish', result: 'Prokuraturaga yuborilgan' },
  { code: '#XT-2026-068', date: '14.06.2026', region: 'Xorazm viloyati', branch: 'Urganch shahar filiali', officer: 'Yetakchi mutaxassis', type: 'HMMQO Xati (Departament)', reason: 'Yerto\'la maydonini noqonuniy xususiylashtirishga ko\'maklashish', result: 'Mehnat shartnomasi bekor qilingan' }
];

// TEZKOR TADBIRLAR (ORGANLAR VA HAMKORLIK PARAMETRLARI BILAN)
window.operationsData = [
  { code: '#TT-2026-08', date: '18.09.2026', region: 'Samarqand viloyati', district: 'Pastdarg\'om filiali', partner: 'Davlat Xavfsizlik Xizmati (DXX)', isCollab: true, proof: '3,000 AQSH dollari', desc: '1.5 gektar ekin yerini noturar joy toifasiga soxtalashtirish evaziga pora olayotganda ushlangan', result: 'JK 210-m bilan jinoyat ishi ochilgan' },
  { code: '#TT-2026-11', date: '04.09.2026', region: 'Samarqand viloyati', district: 'Samarqand shahar filiali', partner: 'Bosh prokuratura huzuridagi Departament', isCollab: true, proof: '15,000,000 so\'m', desc: 'Davlat reyestri elektron bazasiga ruxsatsiz noqonuniy o\'zgartirish kiritish fakti', result: 'JK 209-m (Xizmat soxtakorligi)' },
  { code: '#TT-2026-05', date: '22.08.2026', region: 'Toshkent viloyati', district: 'Qibray tumani filiali', partner: 'Bosh prokuratura huzuridagi Departament', isCollab: false, proof: '5,000 AQSH dollari', desc: 'Auksionsiz berilgan bino kadastr pasportini tayyorlab berish evaziga ushlangan', result: 'JK 168 va 211-m (Qamoq ehtiyot chorasi)' },
  { code: '#TT-2026-09', date: '12.09.2026', region: 'Toshkent viloyati', district: 'Zangiota filiali', partner: 'Davlat Xavfsizlik Xizmati (DXX)', isCollab: true, proof: '2,500 AQSH dollari', desc: 'Qishloq xo\'jaligi yerini yakka tartibda uy-joy qurish uchun noqonuniy rasmiylashtirish', result: 'JK 210-m (Tergovda)' },
  { code: '#TT-2026-02', date: '14.07.2026', region: 'Andijon viloyati', district: 'Asaka tumani filiali', partner: 'Ichki Ishlar Vazirligi (IIB)', isCollab: true, proof: '1,200 AQSH dollari', desc: 'Uy-joy chegaralarini noqonuniy kengaytirib rasmiylashtirish vaqtida ushlangan', result: 'JK 210-m (Sudga yuborilgan)' },
  { code: '#TT-2026-12', date: '25.09.2026', region: 'Buxoro viloyati', district: 'G\'ijduvon filiali', partner: 'Prokuratura organlari', isCollab: false, proof: '3,500 AQSH dollari', desc: 'Tadbirkorga yer ajratish bo\'yicha ijobiy xulosa tayyorlab berish evaziga olingan', result: 'JK 210-m bilan qamoqqa olingan' },
  { code: '#TT-2026-03', date: '19.06.2026', region: 'Xorazm viloyati', district: 'Urganch shahar filiali', partner: 'Bosh prokuratura huzuridagi Departament', isCollab: true, proof: '18,000,000 so\'m', desc: 'Ko\'p qavatli bino ostidagi yerto\'lani xususiylashtirib berish vaqtida ushlangan', result: 'JK 168-m (Firibgarlik)' }
];

// SUDLANGAN XODIMLAR REYESTRI
window.convictedData = [
  { pinfl: '31405901230018', name: 'Karimov Bahodir Shokirovich', region: 'Toshkent viloyati', role: 'Bo\'lim boshlig\'i o\'rinbosari', court: 'Toshkent viloyat JIB sudi', date: '14.01.2025', articles: '205-m, 210-m', punishment: '3 yil axloq tuzatish, 2 yil mansab taqiqi', status: 'chetlatilgan' },
  { pinfl: '31904881120021', name: 'Ergashev Tohir Mansurovich', region: 'Toshkent viloyati', role: 'Yetakchi muhandis', court: 'Qibray tuman sudi', date: '18.04.2025', articles: '168-modda 3-qism', punishment: 'Ozodlikni cheklash, mansab taqiqi', status: 'chetlatilgan' },
  { pinfl: '32004881120034', name: 'Aliyev Vali G\'aniyevich', region: 'Samarqand viloyati', role: 'Yetakchi mutaxassis', court: 'Samarqand shahar sudi', date: '12.03.2024', articles: '167-m 2-qism', punishment: 'Jarima va moddiy zarar', status: 'chetlatilgan' },
  { pinfl: '31802956730055', name: 'Nazarov Ilhom Bobirovich', region: 'Buxoro viloyati', role: 'Katta inspektor', court: 'Buxoro shahar sudi', date: '20.06.2025', articles: '214-modda', punishment: '1 yil mansab taqiqi', status: 'chetlatilgan' },
  { pinfl: '32501913340078', name: 'Qodirov Farrux Rustamovich', region: 'Andijon viloyati', role: 'Arxiv mudiri', court: 'Andijon shahar sudi', date: '15.02.2026', articles: '167-m, 205-m', punishment: 'Ozodlikni cheklash', status: 'chetlatilgan' },
  { pinfl: '30509924510091', name: 'Oripov Jamshid Tohirovich', region: 'Xorazm viloyati', role: 'Muhandis-yer tuzuvchi', court: 'Urganch tuman sudi', date: '04.11.2025', articles: '209-modda (Xizmat soxtakorligi)', punishment: '2 yil axloq tuzatish', status: 'ishlamoqda' }
];

// KORRUPSION XAVF GURUHLARI (A, B, D)
window.riskGroupsData = [
  { pinfl: '32104921230055', name: 'Rahmonov Dilshod Anvarovich', region: 'Samarqand viloyati', role: 'Mulkni ro\'yxatga olish bo\'limi boshlig\'i', type: 'A', desc: 'Yer maydonlarini noqonuniy ro\'yxatga olish va auksionsiz o\'tkazish xavfi', action: 'Doimiy audio/video nazorat ostida', docNum: 'XAVF-SAM-01', docDate: '12.09.2026' },
  { pinfl: '31804901230077', name: 'Valiyev Sardor Olimovich', region: 'Samarqand viloyati', role: 'Katta muhandis', type: 'B', desc: 'Qarindoshlik va tijorat subyektlari bilan yashirin aloqalar', action: 'Boshqa tuman filialiga rotatsiya qilinmoqda', docNum: 'XAVF-SAM-04', docDate: '19.08.2026' },
  { pinfl: '31908851440019', name: 'Ergashev Bobur Tohirovich', region: 'Toshkent viloyati', role: 'Qibray tumani bosh muhandisi', type: 'A', desc: 'Auksionsiz yer maydoniga xulosa tayyorlash xavfi yuqori', action: 'Imzo vakolati cheklangan', docNum: 'XAVF-TOS-04', docDate: '18.09.2026' },
  { pinfl: '32401912230011', name: 'Karimov Jasur Shukurovich', region: 'Andijon viloyati', role: 'Yetakchi mutaxassis', type: 'B', desc: 'Yaqin qarindoshi qurilish firmasida muhandis (Manfaatlar to\'qnashuvi)', action: 'Tasdiqlash komissiyasidan chiqarilgan', docNum: 'XAVF-AND-02', docDate: '05.08.2026' },
  { pinfl: '31502881230099', name: 'Normurodov Ilhom Bobirovich', region: 'Buxoro viloyati', role: 'Katta inspektor', type: 'B', desc: 'Rieltorlik agentligi bilan muntazam yashirin aloqa signali kelgan', action: 'Ichki tekshiruv tayinlangan', docNum: 'XAVF-BUX-09', docDate: '22.09.2026' },
  { pinfl: '32201941230088', name: 'Qosimov Rustam Alisherovich', region: 'Xorazm viloyati', role: 'Arxiv xodimi', type: 'D', desc: 'Hujjatlarni saqlash va nusxalash intizomi sust', action: 'Profilaktik ogohlantirish berilgan', docNum: 'XAVF-XOR-11', docDate: '14.07.2026' }
];

// KOMPLAYENS TASHABBUSI BILAN BO'SHATILGAN XODIMLAR
window.firedStaffData = [
  { name: 'Sultonov Murod G\'aniyevich', region: 'Samarqand viloyati', reason: 'Mansab vakolatini suiiste\'mol qilib egallangan yerga kadastr ochgani', orderNum: '№144-K', orderDate: '14.08.2026', result: 'Mehnat shartnomasi bekor qilingan (MK 161-modda)' },
  { name: 'Bekmurodov Sanjar Alisherovich', region: 'Toshkent viloyati', reason: 'Tadbirkordan hujjatlarni davlat ro\'yxatidan o\'tkazish evaziga noqonuniy haq talab qilgani', orderNum: '№98-K', orderDate: '28.07.2026', result: 'Ishdan chetlatilgan va prokuraturaga yuborilgan' },
  { name: 'Yusupov Jamshid Tohirovich', region: 'Andijon viloyati', reason: 'MCHJ ta\'sischisi ekanligi aniqlanib, tadbirkorlikni to\'xtatishdan bosh tortgani', orderNum: '№112-K', orderDate: '02.09.2026', result: 'Mehnat shartnomasi bekor qilingan' },
  { name: 'Xoliqov Bobur Mirzo', region: 'Xorazm viloyati', reason: 'Xizmat tekshiruvida kadastr ma\'lumotlar bazasiga soxta ma\'lumot kiritgani fosh bo\'lgan', orderNum: '№77-K', orderDate: '19.06.2026', result: 'Lavozimidan ozod etilgan' },
  { name: 'Azizov Ravshan Karimovich', region: 'Qashqadaryo viloyati', reason: 'Yer chegaralarini asossiz ravishda o\'zgartirib dalolatnoma tuzgani aniqlangan', orderNum: '№103-K', orderDate: '11.08.2026', result: 'Mehnat shartnomasi bekor qilingan' }
];

// BIRLASHGAN MANFAATLAR TO'QNASHUVI VA TADBIRKORLIK (STIR)
window.combinedConflictBusinessData = [
  { name: 'Sobirov Mirkomil Rustamovich', pinfl: '31506891230041', region: 'Andijon viloyati', role: '1-toifali mutaxassis', type: 'Tadbirkorlik (STIR)', detail: '"VODIY GEO LOYIHA" MCHJ (STIR: 308291442) 50% ta\'sischisi', action: 'Ulushdan chiqish talabnomasi berilgan' },
  { name: 'Rahmonov Dilshod Anvarovich', pinfl: '32104921230055', region: 'Samarqand viloyati', role: 'Bo\'lim boshlig\'i', type: 'Manfaatlar to\'qnashuvi', detail: 'Ukasi Rahmonov Sanjar — xususiy kadastr muhandisi', action: 'Boshqa tuman filialiga rotatsiya qilingan' },
  { name: 'Ergashev Bobur Tohirovich', pinfl: '31908851440019', region: 'Toshkent viloyati', role: 'Bosh mutaxassis', type: 'Manfaatlar to\'qnashuvi', detail: 'Ayoli Tohirova Madina — rieltorlik agentligi direktori', action: 'Tasdiqlash komissiyasidan chetlatilgan' },
  { name: 'Valiyev Sardor Olimovich', pinfl: '31804901230077', region: 'Samarqand viloyati', role: 'Arxiv mudiri', type: 'Tadbirkorlik (STIR)', detail: '"SAMARQAND AGRO" MCHJ (STIR: 305119842) 25% ulush', action: 'Ulushdan chiqish to\'g'risida ogohlantirilgan' },
  { name: 'Qosimov Rustam Alisherovich', pinfl: '32201941230088', region: 'Xorazm viloyati', role: 'Muhandis', type: 'Tadbirkorlik (YATT)', detail: 'YATT "QOSIMOV RUSTAM" (Faol guvohnoma STIR: 541298411)', action: 'Tadbirkorlik faoliyatini tugatish talab etilgan' }
];
