name: Build KompNazorat 2.1 App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout kod
      uses: actions/checkout@v4

    - name: Node.js o‘rnatish
      uses: actions/setup-node@v4
      with:
        node-version: 18

    - name: Bog‘liqliklarni o‘rnatish
      run: npm install

    - name: Windows ilovasini yig‘ish (Electron Builder)
      run: npm run build
      continue-on-error: false
